version: '3.1'

services:
  # Container do servidor web Ubuntu da aplicação
  php-ubuntu:
    image: slab_php-ubuntu
    build:
      context: php
      dockerfile: ./Dockerfile-ubuntu-prod
    ports:
      - 3000:80
    depends_on:
      - mysql

  # Container do servidor de banco de dados MySQL
  mysql:
    image: slab_mysql
    build:
      context: mysql
      dockerfile: ./Dockerfile
    ports:
      - 13306:3306