version: '3.1'
services:
  php:
    image: slab_php
    build: 
      context: php
      dockerfile: ./Dockerfile-prod
    ports:
      - 3000:80
    depends_on:
      - mysql

  mysql:
    image: slab_mysql
    build: 
      context: mysql
      dockerfile: ./Dockerfile
    ports:
      - 13306:3306