# Jammy version
FROM ubuntu:22.04

WORKDIR /

#ENV DEBIAN_FRONTEND noninteractive

# Exporta o fuso horário para não pedir área geográfica durante as instalações
ENV TZ=America/Sao_Paulo

# Aloca o dado do fuso horário em /etc/timezone
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get install -y apache2 php libapache2-mod-php

WORKDIR /var/www
RUN chmod -r 777 ./html

WORKDIR /var/www/html
RUN rm -f index.html

RUN /etc/init.d/apache2 restart

RUN apt-get install -y r-base php-twig php-intl php-gd php-pdo php-pdo-mysql

RUN apt-get clean