# Jammy version
FROM ubuntu:22.04

WORKDIR /

# ENV DEBIAN_FRONTEND noninteractive

# Exporta o fuso horário para não pedir área geográfica durante as instalações
ENV TZ=America/Sao_Paulo
# Aloca o dado do fuso horário em /etc/timezone
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get -y upgrade && \
    apt-get install -y apache2 php libapache2-mod-php php-mysql php-gd php-xml

WORKDIR /var/www/
RUN chmod -R 777 html/

WORKDIR /var/www/html/
RUN rm -f index.html

COPY src/ .

RUN apt-get install -y composer r-base nodejs npm && \
    php-twig php-intl php-pdo php-pdo-mysql 

# Não é possível instalar snap em um container
RUN chmod -R 777 /var/www/html/configuracoes.json

RUN mkdir /var/www/html/tmp && \ 
    chmod -R 777 /var/www/html/tmp

RUN useradd -m composer && chown -R composer:composer /var/www/html
USER composer

WORKDIR /var/www/html/
RUN composer install

USER root
RUN npm install

CMD ["apache2ctl", "-D", "FOREGROUND"]

#apache2, php, Node, Composer, R, Twig, NPM, PDO, PDO Mysql, INTL, GD